version: "3.7"

services:
  # application
  app:
    image: transneft-app:1.0
    build:
      context: ./backend
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "5001:5000"
    volumes:
      - ./backend/app/:/transneft/application/
      - ./backend/common/:/common/
      - masking_maps:/transneft/masking_maps/
    env_file:
      - ./.env.example
    depends_on:
      - db

#  client:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    ports:
#      - '3000:80'
##    links:
##      - api
#    depends_on:
#      - app

  # The DataBase
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    restart: unless-stopped
    ports:
      - "5432:5432"
    # volumes:
    #   - app_postgres:/var/lib/postgresql/data

volumes:
  # app_postgres:
  masking_maps:
