version: "3.7"

services:
  # application
  app:
    image: transneft-app:1.0
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "5000:5000"
    volumes:
      - ./app/:/transneft/app/
      - ./common/:/common/
    env_file:
      - ./.env.example
    depends_on:
      - db

  # The DataBase
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - app_postgres:/var/lib/postgresql/data

volumes:
  app_postgres:
