version: "3.7"

services:
  # application
  app:
    image: transneft-app:1.0
    build:
      context: ./backend
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "5001:5000"
    volumes:
      - ./backend/app/:/transneft/app/
      - ./common/:/common/
      - masking_maps:/transneft/masking_maps/
    env_file:
      - ./.env.example
    depends_on:
      - db
      - state_cache

  # client:
  #    build:
  #      context: ./frontend
  #      dockerfile: Dockerfile
  #    ports:
  #      - '3000:80'
  #    links:
  #      - app
  #    depends_on:
  #      - app

  # The DataBase
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - app_postgres:/var/lib/postgresql/data

#  consumer:
#    image: consumer:1.0
#    build:
#      context: ./task_manager
#      dockerfile: Dockerfile
#    platform: linux/amd64
#    volumes:
#      - ./common/:/consumer/common/
#    env_file:
#      - ./.env.example
#    depends_on:
#      - db

  state_cache:
    image: redis:7.0-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass pass2
    volumes:
        - cache:/data

volumes:
  app_postgres:
  masking_maps:
  cache:
