"""add is_test and rule fields

Revision ID: 79fef0ceb852
Revises: 60bdf78092ae
Create Date: 2023-05-14 19:25:25.693667

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '79fef0ceb852'
down_revision = '60bdf78092ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('masking_map_file', sa.Column('is_test', sa.Boolean(), nullable=True))
    op.add_column('masking_map_file', sa.Column('params_masking', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('masking_map_file', sa.Column('is_valid', sa.Boolean(), nullable=True))
    op.add_column('rule', sa.Column('compensatory_measures', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rule', 'compensatory_measures')
    op.drop_column('masking_map_file', 'is_valid')
    op.drop_column('masking_map_file', 'params_masking')
    op.drop_column('masking_map_file', 'is_test')
    # ### end Alembic commands ###
