"""del excess relationship

Revision ID: a8c2d874b03b
Revises: 2ea432cdda48
Create Date: 2023-05-21 19:03:48.880992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8c2d874b03b'
down_revision = '2ea432cdda48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('type_work_protection')
    op.drop_column('protection', 'is_need_masking')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('protection', sa.Column('is_need_masking', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_table('type_work_protection',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_protection', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_type_work', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_protection'], ['protection.id'], name='type_work_protection_id_protection_fkey'),
    sa.ForeignKeyConstraint(['id_type_work'], ['type_work.id'], name='type_work_protection_id_type_work_fkey'),
    sa.PrimaryKeyConstraint('id', name='type_work_protection_pkey')
    )
    # ### end Alembic commands ###
