"""add main tables

Revision ID: 3f7db76a83eb
Revises: 
Create Date: 2023-02-16 18:16:57.413633

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3f7db76a83eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type_protection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type_work',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_type_work_name'), 'type_work', ['name'], unique=False)
    op.create_table('protection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('id_type_protection', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_type_protection'], ['type_protection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protection_id_type_protection'), 'protection', ['id_type_protection'], unique=False)
    op.create_index(op.f('ix_protection_name'), 'protection', ['name'], unique=False)
    op.create_table('mn_object',
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('id_protection', sa.Integer(), nullable=True),
    sa.Column('id_parent', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_parent'], ['mn_object.id'], ),
    sa.ForeignKeyConstraint(['id_protection'], ['protection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mn_object_id_parent'), 'mn_object', ['id_parent'], unique=False)
    op.create_table('rules_of_protection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('any_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id_protection', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_protection'], ['protection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type_work_protection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_protection', sa.Integer(), nullable=True),
    sa.Column('id_type_work', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_protection'], ['protection.id'], ),
    sa.ForeignKeyConstraint(['id_type_work'], ['type_work.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('type_work_protection')
    op.drop_table('rules_of_protection')
    op.drop_index(op.f('ix_mn_object_id_parent'), table_name='mn_object')
    op.drop_table('mn_object')
    op.drop_index(op.f('ix_protection_name'), table_name='protection')
    op.drop_index(op.f('ix_protection_id_type_protection'), table_name='protection')
    op.drop_table('protection')
    op.drop_index(op.f('ix_type_work_name'), table_name='type_work')
    op.drop_table('type_work')
    op.drop_table('type_protection')
    # ### end Alembic commands ###
