"""add full_name to loc

Revision ID: 5ecd8d5c4cbb
Revises: b785b6299109
Create Date: 2023-06-05 08:45:53.698390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ecd8d5c4cbb'
down_revision = 'b785b6299109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('full_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location', 'full_name')
    # ### end Alembic commands ###
