"""add fk settings

Revision ID: 7c95bfe4f9c1
Revises: a8c2d874b03b
Create Date: 2023-05-23 10:29:05.860949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c95bfe4f9c1'
down_revision = 'a8c2d874b03b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_criteria_rule', 'criteria', type_='foreignkey')
    op.create_foreign_key("fk_criteria_rule", 'criteria', 'rule', ['rule_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('criteria_location_id_criteria_fkey', 'criteria_location', type_='foreignkey')
    op.drop_constraint('criteria_location_id_location_fkey', 'criteria_location', type_='foreignkey')
    op.create_foreign_key("criteria_location_id_criteria_fkey", 'criteria_location', 'criteria', ['id_criteria'], ['id'], ondelete='SET NULL')
    op.create_foreign_key("criteria_location_id_location_fkey", 'criteria_location', 'location', ['id_location'], ['id'], ondelete='SET NULL')
    op.drop_constraint('criteria_location_type_id_criteria_fkey', 'criteria_location_type', type_='foreignkey')
    op.drop_constraint('criteria_location_type_id_type_location_fkey', 'criteria_location_type', type_='foreignkey')
    op.create_foreign_key("criteria_location_type_id_criteria_fkey", 'criteria_location_type', 'criteria', ['id_criteria'], ['id'], ondelete='SET NULL')
    op.create_foreign_key("criteria_location_type_id_type_location_fkey", 'criteria_location_type', 'location_type', ['id_type_location'], ['id'], ondelete='SET NULL')
    op.drop_constraint('criteria_work_type_id_type_work_fkey', 'criteria_work_type', type_='foreignkey')
    op.drop_constraint('criteria_work_type_id_criteria_fkey', 'criteria_work_type', type_='foreignkey')
    op.create_foreign_key("criteria_work_type_id_type_work_fkey", 'criteria_work_type', 'type_work', ['id_type_work'], ['id'], ondelete='SET NULL')
    op.create_foreign_key("criteria_work_type_id_criteria_fkey", 'criteria_work_type', 'criteria', ['id_criteria'], ['id'], ondelete='SET NULL')
    op.drop_constraint('location_id_parent_fkey', 'location', type_='foreignkey')
    op.drop_constraint('location_id_type_fkey', 'location', type_='foreignkey')
    op.create_foreign_key("location_id_parent_fkey", 'location', 'location_type', ['id_type'], ['id'], ondelete='SET NULL')
    op.create_foreign_key("location_id_type_fkey", 'location', 'location', ['id_parent'], ['id'], ondelete='SET NULL')
    op.drop_constraint('masking_map_file_user_id_fkey', 'masking_map_file', type_='foreignkey')
    op.create_foreign_key("masking_map_file_user_id_fkey", 'masking_map_file', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('protection_id_status_fkey', 'protection', type_='foreignkey')
    op.drop_constraint('protection_id_type_protection_fkey', 'protection', type_='foreignkey')
    op.drop_constraint('protection_id_location_fkey', 'protection', type_='foreignkey')
    op.create_foreign_key("protection_id_status_fkey", 'protection', 'protection_status', ['id_status'], ['id'], ondelete='SET NULL')
    op.create_foreign_key("protection_id_type_protection_fkey", 'protection', 'type_protection', ['id_type_protection'], ['id'], ondelete='SET NULL')
    op.create_foreign_key("protection_id_location_fkey", 'protection', 'location', ['id_location'], ['id'], ondelete='SET NULL')
    op.drop_constraint('question_answer_id_question_fkey', 'question_answer', type_='foreignkey')
    op.create_foreign_key("question_answer_id_question_fkey", 'question_answer', 'question', ['id_question'], ['id'], ondelete='CASCADE')
    op.drop_constraint('rule_user_id_fkey', 'rule', type_='foreignkey')
    op.create_foreign_key("rule_user_id_fkey", 'rule', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('rule_protection_id_protection_fkey', 'rule_protection', type_='foreignkey')
    op.drop_constraint('rule_protection_id_rule_fkey', 'rule_protection', type_='foreignkey')
    op.create_foreign_key("rule_protection_id_protection_fkey", 'rule_protection', 'rule', ['id_rule'], ['id'], ondelete='SET NULL')
    op.create_foreign_key("rule_protection_id_rule_fkey", 'rule_protection', 'protection', ['id_protection'], ['id'], ondelete='SET NULL')
    op.drop_constraint('type_work_departament_id_fkey', 'type_work', type_='foreignkey')
    op.create_foreign_key("type_work_departament_id_fkey", 'type_work', 'departament_of_work', ['departament_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("type_work_departament_id_fkey", 'type_work', type_='foreignkey')
    op.create_foreign_key('type_work_departament_id_fkey', 'type_work', 'departament_of_work', ['departament_id'], ['id'])
    op.drop_constraint("rule_protection_id_rule_fkey", 'rule_protection', type_='foreignkey')
    op.drop_constraint("rule_protection_id_protection_fkey", 'rule_protection', type_='foreignkey')
    op.create_foreign_key('rule_protection_id_rule_fkey', 'rule_protection', 'rule', ['id_rule'], ['id'])
    op.create_foreign_key('rule_protection_id_protection_fkey', 'rule_protection', 'protection', ['id_protection'], ['id'])
    op.drop_constraint("rule_user_id_fkey", 'rule', type_='foreignkey')
    op.create_foreign_key('rule_user_id_fkey', 'rule', 'users', ['user_id'], ['id'])
    op.drop_constraint("question_answer_id_question_fkey", 'question_answer', type_='foreignkey')
    op.create_foreign_key('question_answer_id_question_fkey', 'question_answer', 'question', ['id_question'], ['id'])
    op.drop_constraint("protection_id_location_fkey", 'protection', type_='foreignkey')
    op.drop_constraint("protection_id_type_protection_fkey", 'protection', type_='foreignkey')
    op.drop_constraint("protection_id_status_fkey", 'protection', type_='foreignkey')
    op.create_foreign_key('protection_id_location_fkey', 'protection', 'location', ['id_location'], ['id'])
    op.create_foreign_key('protection_id_type_protection_fkey', 'protection', 'type_protection', ['id_type_protection'], ['id'])
    op.create_foreign_key('protection_id_status_fkey', 'protection', 'protection_status', ['id_status'], ['id'])
    op.drop_constraint("masking_map_file_user_id_fkey", 'masking_map_file', type_='foreignkey')
    op.create_foreign_key('masking_map_file_user_id_fkey', 'masking_map_file', 'users', ['user_id'], ['id'])
    op.drop_constraint("location_id_type_fkey", 'location', type_='foreignkey')
    op.drop_constraint("location_id_parent_fkey", 'location', type_='foreignkey')
    op.create_foreign_key('location_id_type_fkey', 'location', 'location_type', ['id_type'], ['id'])
    op.create_foreign_key('location_id_parent_fkey', 'location', 'location', ['id_parent'], ['id'])
    op.drop_constraint("criteria_work_type_id_criteria_fkey", 'criteria_work_type', type_='foreignkey')
    op.drop_constraint("criteria_work_type_id_type_work_fkey", 'criteria_work_type', type_='foreignkey')
    op.create_foreign_key('criteria_work_type_id_criteria_fkey', 'criteria_work_type', 'criteria', ['id_criteria'], ['id'])
    op.create_foreign_key('criteria_work_type_id_type_work_fkey', 'criteria_work_type', 'type_work', ['id_type_work'], ['id'])
    op.drop_constraint("criteria_location_type_id_type_location_fkey", 'criteria_location_type', type_='foreignkey')
    op.drop_constraint("criteria_location_type_id_criteria_fkey", 'criteria_location_type', type_='foreignkey')
    op.create_foreign_key('criteria_location_type_id_type_location_fkey', 'criteria_location_type', 'location_type', ['id_type_location'], ['id'])
    op.create_foreign_key('criteria_location_type_id_criteria_fkey', 'criteria_location_type', 'criteria', ['id_criteria'], ['id'])
    op.drop_constraint("criteria_location_id_location_fkey", 'criteria_location', type_='foreignkey')
    op.drop_constraint("criteria_location_id_criteria_fkey", 'criteria_location', type_='foreignkey')
    op.create_foreign_key('criteria_location_id_location_fkey', 'criteria_location', 'location', ['id_location'], ['id'])
    op.create_foreign_key('criteria_location_id_criteria_fkey', 'criteria_location', 'criteria', ['id_criteria'], ['id'])
    op.drop_constraint("fk_criteria_rule", 'criteria', type_='foreignkey')
    op.create_foreign_key('fk_criteria_rule', 'criteria', 'rule', ['rule_id'], ['id'])
    # ### end Alembic commands ###
