"""fix attrs

Revision ID: 88c74afcdae7
Revises: c0d197b075f9
Create Date: 2023-05-27 18:49:17.291561

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '88c74afcdae7'
down_revision = 'c0d197b075f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('masking_map_file', sa.Column('logic_machine_answer', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index('ix_task_check_map_file_status', table_name='task_check_map_file')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_task_check_map_file_status', 'task_check_map_file', ['status'], unique=False)
    op.drop_column('masking_map_file', 'logic_machine_answer')
    # ### end Alembic commands ###
