"""fix attrs

Revision ID: b785b6299109
Revises: 88c74afcdae7
Create Date: 2023-06-01 18:06:46.404201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b785b6299109'
down_revision = '88c74afcdae7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_criteria', sa.Column('number_question', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_criteria', 'number_question')
    # ### end Alembic commands ###
