"""add any value

Revision ID: c0d197b075f9
Revises: fbb1a48ca611
Create Date: 2023-05-25 15:05:36.405159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0d197b075f9'
down_revision = 'fbb1a48ca611'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('criteria', sa.Column('is_any', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('criteria', 'is_any')
    # ### end Alembic commands ###
