"""add task check files

Revision ID: fbb1a48ca611
Revises: 7c95bfe4f9c1
Create Date: 2023-05-25 09:01:07.901337

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fbb1a48ca611'
down_revision = '7c95bfe4f9c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_check_map_file',
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_task', sa.String(length=255), nullable=True),
    sa.Column('date_start', sa.DateTime(), nullable=True),
    # sa.Column('status', sa.String(), nullable=True),
    sa.Column('status',
              sa.Enum('pending', 'in_process', 'failed',
                      'success', name='statustask'),
              nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_check_map_file_status'), 'task_check_map_file', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_check_map_file_status'), table_name='task_check_map_file')
    op.drop_table('task_check_map_file')
    # ### end Alembic commands ###
